import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Range from 'App/Models/Range'

export default class extends BaseSeeder {
  public async run () {
    // Write your database queries inside the run method
    await Range.createMany([
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_ISR",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_FONDO_SOLIDARIO",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_FONDO_SOLIDARIO",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_FONDO_SOLIDARIO",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_FONDO_SOLIDARIO",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_INCAPACIDAD_GENERAL",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_INCAPACIDAD_GENERAL",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_INCAPACIDAD_GENERAL",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_INCAPACIDAD_GENERAL",
        start:"",
        end:"",
        value:""
      },
      {
        grouper:"TABLA_INCAPACIDAD_LABORAL",
        start:"",
        end:"",
        value:""
      },
    ])
  }
}
